from database import get_db, init_db
init_db()
db = get_db()
c = db.cursor()
c.execute("DELETE FROM startups")
c.execute("DELETE FROM events")
c.execute("INSERT INTO startups (name, category, stage, description, rating) VALUES (?,?,?,?,?)", ("EasyBreath","HealthTech","MVP","Asthma app and product",4.7))
c.execute("INSERT INTO startups (name, category, stage, description, rating) VALUES (?,?,?,?,?)", ("AdaptMe","HealthTech","Prototype","Students adoptation",4.9))
c.execute("INSERT INTO startups (name, category, stage, description, rating) VALUES (?,?,?,?,?)", ("Qwestly","EdTech","MVP","Platform for surveys",4.8))
c.execute("INSERT INTO events (title, date, location) VALUES (?,?,?)", ("Startup Meetup","2025-12-01","Aqmola Hub"))
c.execute("INSERT INTO events (title, date, location) VALUES (?,?,?)", ("Pizza Pitch","2025-12-10","Aqmola Hub"))
db.commit()
db.close()
print("Test data added.")
